[package]
name = "cricket-rs"
version = "0.1.0"
authors = ["Bhavani Shankar <ebhavanishankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"